/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.Test;
import ru.nsu.fit.g20203.sinyukov.worker.WorkerApplication;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        WorkerApplication classUnderTest = new WorkerApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
