internalApiPrefix:
  /internal/api/worker/hash
springdoc:
  swagger-ui:
    path:
      /
manager:
  baseUrl:
    http://localhost:8080
  apiPrefix:
    /internal/api/manager/hash
  patchHashCrack:
    path:
      /crack/request
server:
  port:
    8081
  error:
    include-message:
      always