internal-api-prefix:
  /internal/api/worker/hash
springdoc:
  swagger-ui:
    path:
      /
manager:
  base-url:
    http://localhost:8080
  api-prefix:
    /internal/api/manager/hash
  patch-hash-crack:
    path:
      /crack/request
server:
  port:
    8081
  error:
    include-message:
      always
spring:
  rabbitmq:
    prefetch-count:
      1