externalApiPrefix:
  /api/hash
internalApiPrefix:
  /internal/api/manager/hash
springdoc:
  swagger-ui:
    path:
      /
alphabet:
  a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
workers:
  urls:
    localhost:8081,
  apiPrefix:
    /internal/api/worker/hash
server:
  error:
    include-message:
      always