/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.g20203.sinyukov.worker;

public class WorkerApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new WorkerApplication().getGreeting());
    }
}
